chessendgame: main.cpp ChessBoard.cpp ChessPiece.cpp KingPiece.cpp RookPiece.cpp GlobalCounter.cpp
	g++ -std=c++0x -o chessendgame main.cpp ChessBoard.cpp ChessPiece.cpp KingPiece.cpp RookPiece.cpp GlobalCounter.cpp -I
